### ISSUE TITLE
only the speaker for which you enter the ip address remains active.

### ISSUE THREAD

**Issue by chali272** [tmjo/heos_custom#4]
I have three speakers, ( 3 x 250 denon heos) all of which can be added if I enter the ip address for them, but only the speaker I enter the ip for stays active and the other goes offline after a few minutes. if I then remove heos and enter ip of  one of the speakers that are not available, then that speaker works again. however, all three speakers are always active in alexa or heos own mobile app the wifi signal is 100% and i tested both 2.4ghz and 5ghz band, it is only in homeassistant they end up as inaccessible if I look in the log nothing is visible. to get the speakers back in home assistant, I havto heos and then pull the cord out of the speakers then they go in for a while before it happens again. sometime, it has worked to enter ip for one of the other speakers and then press update in the heos integration, the others have appeared for a while again.

**Comment by tmjo** [comment]
Hi, that's weird. I've got 4x HEOS and they all seem ok here. Although, I did notice some instabilities last week, but assumed it was due to my (sometimes) poor Wifi. I'll check and see if there are any updates in the official integration that need to be implemented. Can you provide some debug logs to better see what can be going on?

**Comment by chali272** [comment]
> Hi, that's weird. I've got 4x HEOS and they all seem ok here. Although, I did notice some instabilities last week, but assumed it was due to my (sometimes) poor Wifi. I'll check and see if there are any updates in the official integration that need to be implemented. Can you provide some debug logs to better see what can be going on?

this can be closed, the problem was due to settings in unifi, enabled p2p and cross p2p fixt the problem. //Regards

**Comment by tmjo** [comment]
Good to hear it is solved.
